        SUBROUTINE PLOTASCREG(NCBUFF)
        IMPLICIT NONE
        INTEGER NCBUFF
C
        INCLUDE 'dimensions.inc'
C
        INTEGER TRUELEN
        REAL LEECOLUMN
C
        INTEGER L
        INTEGER NCOLASC1(NMAXBUFF),NCOLASC2(NMAXBUFF)
        INTEGER ASCCOLOR(NMAXBUFF)
        INTEGER ASCLWIDTH(NMAXBUFF)
        INTEGER ASCSYMB(NMAXBUFF)
        REAL XMIN,XMAX,YMIN,YMAX
        REAL X,Y
        REAL DX
        REAL ASCCHEIGHT(NMAXBUFF)                        !plot marks from ASCII
        CHARACTER*255 ASCREGFILE(NMAXBUFF)
        CHARACTER*255 CLINEA
        LOGICAL LOGFILE
C
        COMMON/BLKASCREGFILE/ASCREGFILE
        COMMON/BLKASCCOLS1/NCOLASC1,NCOLASC2,ASCCOLOR,ASCLWIDTH,ASCSYMB
        COMMON/BLKASCCOLS2/ASCCHEIGHT
C------------------------------------------------------------------------------
        INQUIRE(FILE=ASCREGFILE(NCBUFF),EXIST=LOGFILE)
        IF(.NOT.LOGFILE)THEN
          WRITE(*,101) 'ERROR: the following file does not exist:'
          L=TRUELEN(ASCREGFILE(NCBUFF))
          WRITE(*,101) ASCREGFILE(NCBUFF)(1:L)
          RETURN
        END IF
C
        CALL PGBBUF
        CALL PGQWIN(XMIN,XMAX,YMIN,YMAX)
        CALL PGSCI(ASCCOLOR(NCBUFF))
        CALL PGSLW(ASCLWIDTH(NCBUFF))
        CALL PGSCH(ASCCHEIGHT(NCBUFF))
C
        OPEN(50,FILE=ASCREGFILE(NCBUFF),STATUS='OLD',FORM='FORMATTED')
10      READ(50,101,END=20) CLINEA
        IF(TRUELEN(CLINEA).GT.0)THEN
          IF(CLINEA(1:1).NE.'#')THEN
            X=LEECOLUMN(CLINEA,NCOLASC1(NCBUFF))
            Y=LEECOLUMN(CLINEA,NCOLASC2(NCBUFF))
            CALL PGPOINT(1,X,Y,ASCSYMB(NCBUFF))
          END IF
        END IF
        GOTO 10
20      CLOSE(50)
        CALL PGSCI(1)
        CALL PGSLW(1)
        CALL PGSCH(1.0)
        CALL PGEBUF
C
101     FORMAT(A)
        END
