        SUBROUTINE PLOTASCREG(NCBUFF)
        IMPLICIT NONE
        INTEGER NCBUFF
!
        INCLUDE 'dimensions.inc'
!
        INTEGER TRUELEN
        REAL LEECOLUMN
!
        INTEGER K,L
        INTEGER NCOLASC1(NMAXBUFF),NCOLASC2(NMAXBUFF)
        INTEGER ASCCOLOR(NMAXBUFF)
        INTEGER ASCLWIDTH(NMAXBUFF)
        INTEGER ASCSYMB(NMAXBUFF)
        INTEGER ASCNUMBER(NMAXBUFF)
        REAL XMIN,XMAX,YMIN,YMAX
        REAL X,Y
        REAL ASCCHEIGHT(NMAXBUFF)                        !plot marks from ASCII
        CHARACTER*255 ASCREGFILE(NMAXBUFF)
        CHARACTER*255 CLINEA
        CHARACTER*255 CDUMMY
        LOGICAL LOGFILE
!
        COMMON/BLKASCREGFILE/ASCREGFILE
        COMMON/BLKASCCOLS1/NCOLASC1,NCOLASC2,ASCCOLOR,ASCLWIDTH,ASCSYMB
        COMMON/BLKASCCOLS2/ASCCHEIGHT,ASCNUMBER
!------------------------------------------------------------------------------
        INQUIRE(FILE=ASCREGFILE(NCBUFF),EXIST=LOGFILE)
        IF(.NOT.LOGFILE)THEN
          WRITE(*,101) 'ERROR: the following file does not exist:'
          L=TRUELEN(ASCREGFILE(NCBUFF))
          WRITE(*,101) ASCREGFILE(NCBUFF)(1:L)
          RETURN
        END IF
!
        CALL PGBBUF
        CALL PGQWIN(XMIN,XMAX,YMIN,YMAX)
        CALL PGSCI(ASCCOLOR(NCBUFF))
        CALL PGSLW(ASCLWIDTH(NCBUFF))
        CALL PGSCH(ASCCHEIGHT(NCBUFF))
!
        OPEN(50,FILE=ASCREGFILE(NCBUFF),STATUS='OLD',FORM='FORMATTED')
        K=0
10      READ(50,101,END=20) CLINEA
        IF(TRUELEN(CLINEA).GT.0)THEN
          IF(CLINEA(1:1).NE.'#')THEN
            K=K+1
            X=LEECOLUMN(CLINEA,NCOLASC1(NCBUFF))
            Y=LEECOLUMN(CLINEA,NCOLASC2(NCBUFF))
            CALL PGPOINT(1,X,Y,ASCSYMB(NCBUFF))
            IF(ASCNUMBER(NCBUFF).EQ.1)THEN
              IF((X.GE.XMIN).AND.(X.LE.XMAX).AND.(Y.GE.YMIN).AND.(Y.LE.YMAX))THEN
                WRITE(CDUMMY,*)K
                CALL RMBLANK(CDUMMY,CDUMMY,L)
                CALL PGPTEXT(X,Y,0.,0.5,CDUMMY(1:L))
              END IF
            END IF
          END IF
        END IF
        GOTO 10
20      CLOSE(50)
        CALL PGSCI(1)
        CALL PGSLW(1)
        CALL PGSCH(1.0)
        CALL PGEBUF
!
101     FORMAT(A)
        END
